const $=s=>document.querySelector(s);let state=null,csrf="";const titles={overview:"组合总览",holdings:"持仓账本",strategy:"本月策略",history:"历史记录",candidates:"候选池",backtest:"回测分析",settings:"设置"};
async function api(path,body){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-SalaryGo-CSRF":csrf},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(v.message||v.error);return v}
function money(v,c="CNY"){return new Intl.NumberFormat("zh-CN",{style:"currency",currency:c,maximumFractionDigits:2}).format(v||0)}
function pct(v){return `${((v||0)*100).toFixed(1)}%`}
function notice(text="",ok=false){const el=$("#notice");el.textContent=text;el.style.background=ok?"#e3f4e9":"";el.style.color=ok?"#245e3c":""}
async function load(){const r=await fetch("/api/state");state=await r.json();csrf=state.csrf_token;render()}
function bars(target,items){const el=$(target);if(!items?.length){el.className="bar-chart empty";el.textContent="暂无数据";return}el.className="bar-chart";el.innerHTML=items.map(x=>`<div class="bar-row"><span>${x.key}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,(x.known_value_share||0)*100)}%"></div></div><strong>${pct(x.known_value_share)}</strong></div>`).join("")}
function render(){const v=state.valuation;$("#total-value").textContent=v?money(v.known_market_value,v.base_currency):"—";$("#coverage").textContent=v?(v.complete?"所有持仓价格完整":"部分持仓缺价格或汇率"):"等待录入持仓";const buckets=v?.concentration?.bucket||[];const risk=buckets.filter(x=>["index_core","individual_stock"].includes(x.key)).reduce((a,x)=>a+(x.known_value_share||0),0);$("#risk-share").textContent=v?pct(risk):"—";bars("#bucket-chart",buckets);bars("#account-chart",v?.concentration?.account||[]);bars("#currency-chart",v?.concentration?.currency||[]);drawHistory();const latest=state.strategies?.[0];$("#latest-strategy").textContent=latest?latest.strategy_id.slice(-13):"暂无";$("#latest-status").textContent=latest?latest.execution_status:"等待第一次生成";const readiness=state.readiness||{};$("#health-list").innerHTML=Object.entries(readiness).map(([k,x])=>`<div class="health-item ${x?"ready":"missing"}"><strong>${x?"已就绪":"待完成"}</strong>${({profile:"用户档案",ledger:"持仓账本",market:"市场数据",allocation_context:"分配规则"})[k]}</div>`).join("");renderHoldings();renderHistory();renderCandidates();renderTemperature();$("#profile-json").value=JSON.stringify(state.profile||{},null,2);$("#ledger-json").value=JSON.stringify(state.ledger||{},null,2);$("#context-json").value=JSON.stringify(state.allocation_context||{},null,2);const quoteTimes=Object.values(state.market?.quotes||{}).map(x=>x.as_of).sort();$("#data-time").textContent=quoteTimes.length?`数据：${quoteTimes.at(-1).slice(0,10)}`:"尚未刷新"}
function drawHistory(){const items=state.valuation_history||[],canvas=$("#history-chart"),empty=$("#history-empty");if(items.length<2){canvas.style.display="none";empty.style.display="block";return}canvas.style.display="block";empty.style.display="none";const dpr=window.devicePixelRatio||1,w=canvas.clientWidth||400,h=130;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const vals=items.map(x=>x.known_market_value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;ctx.strokeStyle="#176b4d";ctx.lineWidth=2;ctx.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1)*(w-16)+8,y=h-12-(v-min)/range*(h-24);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function renderHoldings(){const body=$("#holding-rows"),items=state.ledger?.holdings||[],ins=Object.fromEntries((state.ledger?.instruments||[]).map(x=>[x.id,x])),acc=Object.fromEntries((state.ledger?.accounts||[]).map(x=>[x.id,x])),vals=Object.fromEntries((state.valuation?.holdings||[]).map(x=>[x.holding_id,x]));body.innerHTML=items.map(h=>`<tr><td>${acc[h.account_id]?.name||h.account_id}</td><td><strong>${ins[h.instrument_id]?.name||h.instrument_id}</strong><br>${ins[h.instrument_id]?.symbol||""}</td><td>${h.quantity}</td><td>${h.average_cost} ${h.cost_currency}</td><td>${h.current_price??"缺失"}</td><td>${vals[h.id]?.market_value==null?"—":money(vals[h.id].market_value,state.ledger.base_currency)}</td><td>${h.price_as_of?.slice(0,10)||"—"}</td><td><button class="secondary edit-holding" data-id="${h.id}">编辑</button></td></tr>`).join("");$("#holdings-empty").style.display=items.length?"none":"block";document.querySelectorAll(".edit-holding").forEach(b=>b.onclick=()=>openHolding(b.dataset.id))}
function openHolding(id=null){if(!state.ledger){notice("请先在设置中保存账户和标的");return}const f=$("#holding-form"),h=id?state.ledger.holdings.find(x=>x.id===id):null;f.elements.account_id.innerHTML=state.ledger.accounts.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");f.elements.instrument_id.innerHTML=state.ledger.instruments.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");f.elements.id.value=id||"";f.elements.account_id.value=h?.account_id||state.ledger.accounts[0]?.id||"";f.elements.instrument_id.value=h?.instrument_id||state.ledger.instruments[0]?.id||"";f.elements.account_id.disabled=!!h;f.elements.instrument_id.disabled=!!h;f.elements.quantity.value=h?.quantity||0;f.elements.average_cost.value=h?.average_cost||0;f.elements.current_price.value=h?.current_price??"";$("#holding-dialog").showModal()}
function renderHistory(){const el=$("#strategy-history"),items=state.strategies||[];if(!items.length){el.className="timeline empty";el.textContent="暂无策略";return}el.className="timeline";el.innerHTML=items.map(x=>`<div class="timeline-item"><span>${x.generated_at.slice(0,10)}</span><strong>${x.user_request}</strong><span>${x.execution_status}</span></div>`).join("")}
function renderCandidates(){const el=$("#candidate-list"),assign=state.candidate_pool?.current?.assignments||[];if(!assign.length){el.className="candidate-list empty";el.textContent="尚未建立候选池";return}el.className="candidate-list";el.innerHTML=assign.map(x=>`<div class="candidate-card"><strong>${x.slot_id}</strong><span>主产品：${x.main?.product_id||"空缺"} · 备用：${x.backup?.product_id||"空缺"}</span><p>${x.selection_reason}</p></div>`).join("")}
function renderTemperature(){const score=[...(state.scores?.records||[])].reverse().find(x=>x.temperature!=null),el=$("#temperature-chart");if(!score){el.className="bar-chart empty";el.textContent="暂无评分";return}bars("#temperature-chart",Object.entries(score.components).map(([key,x])=>({key,known_value_share:x.score/100})))}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(`#${b.dataset.view}`).classList.add("active");$("#page-title").textContent=titles[b.dataset.view]})
$("#add-holding").onclick=()=>openHolding();$("#holding-save").onclick=async e=>{e.preventDefault();try{const f=$("#holding-form"),id=f.elements.id.value,isNew=!id,instrument=state.ledger.instruments.find(x=>x.id===f.elements.instrument_id.value),price=f.elements.current_price.value===""?null:+f.elements.current_price.value,record={quantity:+f.elements.quantity.value,average_cost:+f.elements.average_cost.value,current_price:price,price_as_of:price==null?null:new Date().toISOString(),data_source:price==null?null:"manual"};if(isNew)Object.assign(record,{id:`holding-${Date.now()}`,account_id:f.elements.account_id.value,instrument_id:f.elements.instrument_id.value,cost_currency:instrument.currency,price_currency:instrument.currency,notes:"页面手动录入"});await api("/api/ledger/mutate",{entity:"holding",action:isNew?"add":"update",id:id||null,record});$("#holding-dialog").close();await load();notice("持仓已保存",true)}catch(e){notice(e.message)}};
$("#generate-strategy").onclick=async()=>{try{const r=await api("/api/strategies/generate",{text:$("#strategy-text").value});if(r.status==="needs_input"){$("#strategy-result").innerHTML=`<div class="risk-note">${r.questions.join("<br>")}</div>`;return}if(r.status==="blocked"){$("#strategy-result").innerHTML=`<div class="risk-note">${r.message}</div>`;return}const p=r.strategy.plan,pre=state.allocation_context?.current?.bucket_values||{};$("#strategy-result").innerHTML=`<div class="panel-head"><h2>本次建议</h2><span>已通过风控并保存</span></div>${p.recommendations.map(x=>`<div class="recommendation"><strong>${x.operation==="buy"?"买入":"暂留现金"} ${x.name}</strong><span>${x.platform} · ${x.funding_currency} ${x.amount.toFixed(2)} · ${x.reason_codes.join(" / ")}</span></div>`).join("")}<h2>配置前后</h2>${Object.keys(p.post_bucket_values).map(k=>`<div class="bar-row"><span>${k}</span><span>${money(pre[k]||0,p.base_currency)} → ${money(p.post_bucket_values[k],p.base_currency)}</span><strong>${pct(p.post_bucket_values[k]/p.post_total_base)}</strong></div>`).join("")}<div class="risk-note">目标收益不保证实现；请在券商中自行确认并执行。</div>`;await load()}catch(e){notice(e.message)}};
$("#refresh-button").onclick=async()=>{try{const req=(state.ledger?.instruments||[]).map(x=>({key:x.id,kind:x.asset_type==="stock"?"stock":"fund",symbol:x.symbol}));if(!req.length)throw new Error("请先录入持仓标的");await api("/api/market/refresh-demo",{requests:req});await load();notice("测试数据刷新完成；请勿将其视作真实行情",true)}catch(e){notice(e.message)}};
async function saveJson(path,key,selector){try{const value=JSON.parse($(selector).value),body={};body[key]=value;if(key==="profile"||key==="ledger")body.expected_revision=value.revision||0;await api(path,body);await load();notice("校验并保存成功",true)}catch(e){notice(e.message)}}
$("#save-profile").onclick=()=>saveJson("/api/profile","profile","#profile-json");$("#save-ledger").onclick=()=>saveJson("/api/ledger","ledger","#ledger-json");$("#save-context").onclick=()=>saveJson("/api/allocation-context","context","#context-json");
$("#run-backtest").onclick=async()=>{try{const config=await fetch("/api/demo/backtest").then(r=>r.json());const r=await api("/api/backtest",{config});const rows=r.report.results.map(x=>`<tr><td>${x.net.strategy}</td><td>${x.net.ending_value.toFixed(2)}</td><td>${x.net.total_fees.toFixed(2)}</td><td>${pct(x.net.maximum_drawdown)}</td></tr>`).join("");$("#backtest-result").innerHTML=`<div class="panel-head"><h2>回测结果</h2><span>${r.report.data_as_of}</span></div><table class="backtest-table"><thead><tr><th>策略</th><th>期末价值</th><th>费用</th><th>最大回撤</th></tr></thead><tbody>${rows}</tbody></table><div class="risk-note">${r.report.disclaimer}</div>`}catch(e){notice(e.message)}};
load().catch(e=>notice(`加载失败：${e.message}`));
